services:
  - type: web
    name: invoice-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: invoice-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: invoice-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: invoice-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: invoice-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: invoice-db
          property: password
    autoDeploy: true

databases:
  - name: invoice-db
    databaseName: invoice_db
    user: postgres
    plan: free
    ipAllowList: [] 